### ISSUE TITLE
In IE11, media queries in style tags with data-senna-track attributes are applied as though the page has a width of 0px

### ISSUE THREAD

**Issue by holatuwol** [liferay/senna.js#301] opened 2019-05-21 01:39 UTC
### Expected behaviour

In all browsers that support media queries, media queries in `<style data-senna-track="temporary">` tags are applied according to the true page width.

### Actual behaviour

In IE11, media queries in `<style data-senna-track="temporary">` and `<style data-senna-track="permanent">` tags are applied as though the page has a width of 0px.

### Steps to reproduce

1. Add the following style tag to the head element of `examples/static_surface/index.html`, `examples/static_surface/foo.html`, and `examples/static_surface/bar.html`

```css
<style data-senna-track="temporary">
@media screen and (max-width: 0px) {
  #header {
    color: red;
  }
}

#content {
  color: red;
}
</style>
```

2. Run `gulp server` (or `node node_modules/gulp/bin/gulp.js server` if you did not install gulp globally) to start a server on localhost:8888
3. Navigate to http://localhost:8888/examples/static_surface/index.html
4. Interact with the updated static_surface example and observe that the header text is changing to red, even though only the content should be red
5. Replace `"temporary"` with `"permanent"` in the added style tag in `examples/static_surface/index.html`, `examples/static_surface/foo.html`,, `examples/static_surface/bar.html`
6. Interact with the updated static_surface example and observe that the header text is changing to red, even though only the content should be red
7. Remove the `data-senna-track` element from the added style tag in `examples/static_surface/index.html`, `examples/static_surface/foo.html`, `examples/static_surface/bar.html`
8. Interact with the updated static_surface example, and observe that everything now works as expected (the header text does not change colors)

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

### Additional notes

Essentially, the fix for https://github.com/liferay/senna.js/issues/124 was incorrect, because the problem affected both `style data-senna-track="temporary"` tags in addition to `link rel="stylesheet" data-senna-track="temporary"` tags.

**Comment by holatuwol** [comment] 2019-06-04 00:24
Note that everything works if senna.js doesn't process style tags in IE.

https://github.com/holatuwol/senna.js/commit/a993e0363a26afa84ab6aa533d3d624e32194e50

**Comment by holatuwol** [comment] 2019-06-04 23:00
Related to [LPS-92572](https://issues.liferay.com/browse/LPS-92572).

**Comment by matuzalemsteles** [comment] 2019-06-17 15:12
hey @holatuwol, just taking a quick look at it, but I'll look into this in more depth this week to reap our options. This is a bit old, I can not remember which ticket we took and what the resolution was. But I put the words of Chema here https://github.com/metal/metal.js/issues/383#issuecomment-414311006 where is the problem.

Even if we stopped tracking the style to solve this, it would not work, since in each navigation Senna will have to take the style and add the page again. Also it is not a problem to add the style in order on the page, I remember @diegonvs spent a few days trying to understand how it worked in IE, it seems that handling this via JavaScript in IE does not recompose correctly the same CSS even adding in the correct order.

**Comment by diegonvs** [comment] 2019-06-19 17:34
Hey @holatuwol, I added some comments here https://issues.liferay.com/browse/LPS-92572

**Comment by duracell80** [comment] 2019-09-23 15:54
Hey just to let you guys know, this issue is possibly causing our videos to load to with "blurry thumbnails" in IE11 when using senna navigation (mainly clicking a breadcrumb item). Essentially loading the page without senna (direct hit) will bring in full HD version of the thumbnail. Navigating with senna then tricks our third party vendor player into thinking it's rendering on mobile and thus it serves us a low resolution image (around 100px wide). 

I'm still trying to figure out how to word it for successful reproduction in Liferay support, not hopeful it will get through LESA to you guys. But yeah this would seems to be an explanation of what I'm seeing and it does impact more than this.

I think it's causing our web content templates to trip into "mobile view" also. We make a few tweaks to get our web content positioned and tweaked and such for mobile display. Senna seems to be tripping IE into those media queries thus showing mobile styles to a desktop browser.

**Comment by holatuwol** [comment] 2019-09-23 17:53
@duracell80 : My understanding is that the senna.js team has determined that this isn't an issue that can be fixed, since it boils down to a bug in IE11.

On the support side, we've provided fixes to disable senna in Liferay on IE11 for some customers who were concerned about the page rendering time performance regression introduced by https://github.com/liferay/senna.js/issues/124 (to summarize, a side-effect of that fix is that IE11 will always re-download every CSS file on every senna-managed page navigation), getting a fix for this issue as a side-effect.

If you want to leave senna enabled, there might be a way to fix this issue from the Liferay backend, which I've described in [LPS-92572](https://issues.liferay.com/browse/LPS-92572?focusedCommentId=1960474&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1960474). However, whether it will fix your thumbnail issue with Kaltura remains to be seen, because it's not clear from your current steps to reproduce that the Kaltura issue is due to a media query that IE11 is processing incorrectly.

**Comment by duracell80** [comment] 2019-09-23 19:56
Yup I understand IE pain. I can't re-write Kaltura's stylesheets to have min and max in the media query and other customers can't rewrite thrid party vendor software to account for bugs that other third parties won't fix. 

I can't re-write senna either so turning it off for IE would be the only solution. I would take slow page loading on a dead browser over mobile css in a desktop browser any day.

Unfortunately over 50% of our users use IE11 and that rises to 72% for the portal homepage which is where the issue is most visible. This situation really sucks. Liferay have to understand that IE is more popular than Edge in the enterprise, it just is, there's no other way of saying that Liferay is starting to fail for enterprise users who can't use Chrome. Not fixing issues particularity for read only browsing for IE11 just plays into Sharepoint's hands.

**Comment by holatuwol** [comment] 2019-09-24 02:09
@duracell80 : Those browser usage statistics aren't unusual. My understanding is that browser's continued dominance internationally is what pushed the product team to leave IE11 on the Liferay compatibility matrix for 7.2 with "limited" support, even though Microsoft itself has stopped supporting the browser.

Because SPA is included through a top head [dynamic include](https://portal.liferay.dev/docs/7-2/customization/-/knowledge_base/c/dynamic-includes), the change to disable SPA for IE11 is straightforward: an if statement at the beginning of [SPATopHeadJSPDynamicInclude](https://github.com/liferay/liferay-portal/blob/7.2.0-ga1/modules/apps/frontend-js/frontend-js-spa-web/src/main/java/com/liferay/frontend/js/spa/web/internal/servlet/taglib/SPATopHeadJSPDynamicInclude.java#L59) to check the browser.

If you haven't gotten things working already (your comment on the LPS leaves me with the impression that you've already got a workaround in place), you can:

1. create a new component with the required changes and blacklist the existing one,
2. replace the corresponding bundle with a marketplace override, or
3. ask through a Help Center ticket if you can get a hotfix that provides the necessary changes

**Comment by duracell80** [comment] 2019-09-24 03:21
Gotcha and kinda surprising that Liferay would even consider cutting IE11 from 7.2. That would have put Enterprise in an un-upgradable looking for another vendor position.

I opened a feature request to have an easier, less code / no code solution in DXP. It's certainly a personal opinion but I don't go for customization like that. Particularly as this is an issue for Liferay to solve and not for each individual lead developer to solve for their install.

The hotfix sounds ok in isolation but I've certainly run into issues where a hot fix leads to even more instability so that's not ideal either.

If it's a trivial change can't Senna be configurable through a control panel UI? Flip a toggle and IE gets senna disabled.

**Comment by julien** [comment] 2019-09-24 12:02
I'm far from being a css expert, but this is what I found so far while testing this. 

I tested with various changes and this is the only way I found so far for the style to be applied correcly in IE 11.

```css
@media all and (min-width: 1px) and (max-width: 1px) {
  #header {
    color: red;
  }
}
```

This is pretty strange because an html file with the same style declaration as describred in the issue but without senna works as expected in IE11. Will continue to investigate.

**Comment by duracell80** [comment] 2019-09-24 13:35
Setting both max and min width is given as a solution to stop mobile breakpoints leaking to desktop IE.

It might be a different issue but I'm finding that IE is applying mobile breakpoints when navigating with Senna. The only fix is to turn Senna off on the links and that then resolves the issue for say a user clicking the portal logo to return to the homepage. 

The style tags in the web content templates don't have the data-senna-track="temporary" attribute.

**Comment by julien** [comment] 2019-09-25 11:05
Hey @duracell80,

I know and understand you don't have access to those external stylesheets or 3rd party css in iframes, I just wanted to see if there was a condition under which the style would "work" in IE.

Disabling senna.js for IE11 might solve this case but it might bring up other issues.

In anycase, I'll continue investigating and discuss this issue with the team to see if  we can come up with a good solution.

**Comment by duracell80** [comment] 2019-09-25 12:45
In my experience at least with DXP in IE11 ... Senna causes so many issues. Pages seem to load a lot faster in IE with SPA off.

The downsides outweigh the advantages, particularly because Senna is so Javascript heavy it feels like older browsers that don't process javascript as well all that processing seems to make the UX worse.

**Comment by wincent** [comment] 2021-04-20 17:46
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?

**Closed by wincent** 2021-04-20 17:46 UTC
